text = input("Enter a string:")
print(len(text))
print(text.isalpha())
print(text.find('x'))
new_text = input("Enter another string:")
print(new_text.replace('e', 'E'))
user_input = input("Enter the user input string:")
print(user_input.count(user_input[0]))
print(user_input.count(user_input[-1]))
